name: Magento 2 BDD E2E Testing Suite Self Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-selftest:
    runs-on: windows-latest

    env:
      PLAYWRIGHT_BASE_URL: https://hyva-demo.elgentos.io/
      PLAYWRIGHT_PRODUCTION_URL: https://hyva-demo.elgentos.io/
      PLAYWRIGHT_STAGING_URL: https://hyva-demo.elgentos.io/

      MAGENTO_ADMIN_SLUG: ${{ secrets.MAGENTO_ADMIN_SLUG }}
      MAGENTO_ADMIN_USERNAME: ${{ secrets.MAGENTO_ADMIN_USERNAME }}
      MAGENTO_ADMIN_PASSWORD: ${{ secrets.MAGENTO_ADMIN_PASSWORD }}

      MAGENTO_NEW_ACCOUNT_PASSWORD: ${{ secrets.MAGENTO_NEW_ACCOUNT_PASSWORD }}
      MAGENTO_EXISTING_ACCOUNT_EMAIL_CHROMIUM: ${{ secrets.MAGENTO_EXISTING_ACCOUNT_EMAIL_CHROMIUM }}
      MAGENTO_EXISTING_ACCOUNT_EMAIL_FIREFOX: ${{ secrets.MAGENTO_EXISTING_ACCOUNT_EMAIL_FIREFOX }}
      MAGENTO_EXISTING_ACCOUNT_EMAIL_WEBKIT: ${{ secrets.MAGENTO_EXISTING_ACCOUNT_EMAIL_WEBKIT }}
      MAGENTO_EXISTING_ACCOUNT_PASSWORD: ${{ secrets.MAGENTO_EXISTING_ACCOUNT_PASSWORD }}
      MAGENTO_EXISTING_ACCOUNT_CHANGED_PASSWORD: ${{ secrets.MAGENTO_EXISTING_ACCOUNT_CHANGED_PASSWORD }}

      MAGENTO_COUPON_CODE_CHROMIUM: ${{ secrets.MAGENTO_COUPON_CODE_CHROMIUM }}
      MAGENTO_COUPON_CODE_FIREFOX: ${{ secrets.MAGENTO_COUPON_CODE_FIREFOX }}
      MAGENTO_COUPON_CODE_WEBKIT: ${{ secrets.MAGENTO_COUPON_CODE_WEBKIT }}

      CAPTCHA_BYPASS: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Copy config files
        run: |
          cp playwright.config.example.ts playwright.config.ts
          cp bypass-captcha.config.example.ts bypass-captcha.config.ts
          cp tests/base/config/test-toggles.example.json tests/base/config/test-toggles.json

      - name: Run Playwright setup test
        run: npx playwright test --reporter=line --workers=4 tests/base/setup.spec.ts
        env:
          CI: true

      - name: Run Playwright tests
        run: npx playwright test --workers=4 --grep-invert "@setup" --max-failures=1
        env:
          CI: true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
